# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgd.proto',
  package='sgd_grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tsgd.proto\x12\x08sgd_grpc\"\x18\n\nOkResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"#\n\x13NotificationRequest\x12\x0c\n\x04user\x18\x01 \x01(\x05\"\'\n\x14NotificationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"8\n\x17SendNotificationRequest\x12\x0c\n\x04user\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\nBotRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0b\x42otResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xde\x01\n\x03SGD\x12R\n\rNotifications\x12\x1d.sgd_grpc.NotificationRequest\x1a\x1e.sgd_grpc.NotificationResponse\"\x00\x30\x01\x12M\n\x10SendNotification\x12!.sgd_grpc.SendNotificationRequest\x1a\x14.sgd_grpc.OkResponse\"\x00\x12\x34\n\x03\x42ot\x12\x14.sgd_grpc.BotRequest\x1a\x15.sgd_grpc.BotResponse\"\x00\x62\x06proto3'
)




_OKRESPONSE = _descriptor.Descriptor(
  name='OkResponse',
  full_name='sgd_grpc.OkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='sgd_grpc.OkResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=47,
)


_NOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='NotificationRequest',
  full_name='sgd_grpc.NotificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='sgd_grpc.NotificationRequest.user', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=84,
)


_NOTIFICATIONRESPONSE = _descriptor.Descriptor(
  name='NotificationResponse',
  full_name='sgd_grpc.NotificationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='sgd_grpc.NotificationResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=125,
)


_SENDNOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='SendNotificationRequest',
  full_name='sgd_grpc.SendNotificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='sgd_grpc.SendNotificationRequest.user', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='sgd_grpc.SendNotificationRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=183,
)


_BOTREQUEST = _descriptor.Descriptor(
  name='BotRequest',
  full_name='sgd_grpc.BotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='sgd_grpc.BotRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=214,
)


_BOTRESPONSE = _descriptor.Descriptor(
  name='BotResponse',
  full_name='sgd_grpc.BotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='sgd_grpc.BotResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=246,
)

DESCRIPTOR.message_types_by_name['OkResponse'] = _OKRESPONSE
DESCRIPTOR.message_types_by_name['NotificationRequest'] = _NOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['NotificationResponse'] = _NOTIFICATIONRESPONSE
DESCRIPTOR.message_types_by_name['SendNotificationRequest'] = _SENDNOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['BotRequest'] = _BOTREQUEST
DESCRIPTOR.message_types_by_name['BotResponse'] = _BOTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OkResponse = _reflection.GeneratedProtocolMessageType('OkResponse', (_message.Message,), {
  'DESCRIPTOR' : _OKRESPONSE,
  '__module__' : 'sgd_pb2'
  # @@protoc_insertion_point(class_scope:sgd_grpc.OkResponse)
  })
_sym_db.RegisterMessage(OkResponse)

NotificationRequest = _reflection.GeneratedProtocolMessageType('NotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONREQUEST,
  '__module__' : 'sgd_pb2'
  # @@protoc_insertion_point(class_scope:sgd_grpc.NotificationRequest)
  })
_sym_db.RegisterMessage(NotificationRequest)

NotificationResponse = _reflection.GeneratedProtocolMessageType('NotificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONRESPONSE,
  '__module__' : 'sgd_pb2'
  # @@protoc_insertion_point(class_scope:sgd_grpc.NotificationResponse)
  })
_sym_db.RegisterMessage(NotificationResponse)

SendNotificationRequest = _reflection.GeneratedProtocolMessageType('SendNotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDNOTIFICATIONREQUEST,
  '__module__' : 'sgd_pb2'
  # @@protoc_insertion_point(class_scope:sgd_grpc.SendNotificationRequest)
  })
_sym_db.RegisterMessage(SendNotificationRequest)

BotRequest = _reflection.GeneratedProtocolMessageType('BotRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOTREQUEST,
  '__module__' : 'sgd_pb2'
  # @@protoc_insertion_point(class_scope:sgd_grpc.BotRequest)
  })
_sym_db.RegisterMessage(BotRequest)

BotResponse = _reflection.GeneratedProtocolMessageType('BotResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOTRESPONSE,
  '__module__' : 'sgd_pb2'
  # @@protoc_insertion_point(class_scope:sgd_grpc.BotResponse)
  })
_sym_db.RegisterMessage(BotResponse)



_SGD = _descriptor.ServiceDescriptor(
  name='SGD',
  full_name='sgd_grpc.SGD',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=249,
  serialized_end=471,
  methods=[
  _descriptor.MethodDescriptor(
    name='Notifications',
    full_name='sgd_grpc.SGD.Notifications',
    index=0,
    containing_service=None,
    input_type=_NOTIFICATIONREQUEST,
    output_type=_NOTIFICATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendNotification',
    full_name='sgd_grpc.SGD.SendNotification',
    index=1,
    containing_service=None,
    input_type=_SENDNOTIFICATIONREQUEST,
    output_type=_OKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Bot',
    full_name='sgd_grpc.SGD.Bot',
    index=2,
    containing_service=None,
    input_type=_BOTREQUEST,
    output_type=_BOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SGD)

DESCRIPTOR.services_by_name['SGD'] = _SGD

# @@protoc_insertion_point(module_scope)
